name: common
description: A new Flutter package project.
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_translate: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  logger: ^1.1.0
  timeago: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

