name: info_screen_plus_plus
description: Next generation info screen for the Raspiblitz
publish_to: 'none' 

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  timeago: ^3.1.0
  flutter_spinkit: ^5.1.0
  material_design_icons_flutter: ^5.0.6595
  flutter_layout_grid: ^1.0.3

  authentication:
    path: ../../authentication
  common:
    path: ../../common
  common_blocs:
    path: ../../common_blocs
  subscription_repository:
    path: ../../subscription_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
